### ISSUE TITLE
Path issue on MacOS

### ISSUE THREAD

**Issue by codingwatching** [DevBobcorn/MarkovCraft#1]
Hi @DevBobcorn 
Your project is really awesome! I love this! Thank you so much for creating it

For the newest feature, download, we need to fix the path to run on MacOS

<img width="649" alt="image" src="https://user-images.githubusercontent.com/85933804/234176428-a5c86748-6ba3-423c-868e-acf9640c35c4.png">

We should use Path.DirectorySeparatorChar instead of \, for example

````
  
        public static string GetPacksDirectory()
        {
            return Directory.GetParent(Application.dataPath).FullName + @$"{Path.DirectorySeparatorChar}Resource Packs";
        }
  
```
So maybe we should create a helper function to correct all the current \

Thank you so much and have a nice day!

**Comment by DevBobcorn** [comment]
Thanks for that feedback! I'll fix this soon :)

**Comment by DevBobcorn** [comment]
I've replaced all slash characters in directories (7e43d069e135b6ec6c768837e2f57b6df1d03fab), and paths should work fine on macOS now
