### ISSUE TITLE
App took toooooooooooooooooooo more RAM

### ISSUE THREAD

**Issue by MoYuan-CN** [DevBobcorn/MarkovCraft#2]
![image](https://github.com/DevBobcorn/MarkovCraft/assets/109946426/c241d53c-3ae7-45e9-b6f5-16eb471a38bb)
Look at this
So it let my minecraft crash

**Comment by DevBobcorn** [comment]
可以附一下使用的生成模型和参数吗？

**Comment by DevBobcorn** [comment]
应该是Entity Graphics包中bug导致的内存泄漏，此问题已在0.14.0版本中[修复](https://docs.unity3d.com/Packages/com.unity.entities.graphics@1.0/changelog/CHANGELOG.html#0140---2021-09-17)。
