### ISSUE TITLE
要不然把这东西提交到winget列表吧

### ISSUE THREAD

**Issue by BUGProtectionAssociation** [DevBobcorn/MarkovCraft#3]
[提交上去嗯嘛啊](https://github.com/microsoft/winget-pkgs)
这样就方便更新了
![image](https://github.com/DevBobcorn/MarkovCraft/assets/65578116/d75444f4-427c-43c4-a18b-df364199f692)

**Comment by DevBobcorn** [comment]
做得不是很完善，暂时没有这样的打算。
