### ISSUE TITLE
Can not load Block Data 

### ISSUE THREAD

**Issue by codingwatching** [DevBobcorn/MarkovCraft#5]
@DevBobcorn 
Please help me fix this error. I see that the vanilla-1.16.5 folder has been successfully downloaded, but then the program needs to find the blocks-1.16.json file in the Extra Data/blocks folder. I have searched in the program's folders but can't find it; I only see a similar folder in the CornModel project, but it seems the file name is not correct either.
Thank you so much!
```
Block data not complete!
UnityEngine.Debug:LogWarning (object)
CraftSharp.BlockStatePalette:PrepareData (string,CraftSharp.DataLoadFlag) (at ./Library/PackageCache/com.devbobcorn.craftsharp@3a936c69d0/Runtime/Scripts/BlockStatePalette.cs:273)
MarkovCraft.GameScene/<>c__DisplayClass25_0:<LoadMCBlockData>b__0 () (at Assets/Scripts/GameScene.cs:171)
System.Threading._ThreadPoolWaitCallback:PerformWaitCallback ()


Block data loading failed
UnityEngine.Debug:LogWarning (object)
MarkovCraft.GameScene/<LoadMCBlockData>d__25:MoveNext () (at Assets/Scripts/GameScene.cs:195)
UnityEngine.SetupCoroutine:InvokeMoveNext (System.Collections.IEnumerator,intptr) (at /Users/bokken/build/output/unity/unity/Runtime/Export/Scripting/Coroutines.cs:17)

```
<img width="1389" alt="Screenshot 2024-04-09 at 10 51 54" src="https://github.com/DevBobcorn/MarkovCraft/assets/85933804/5005b15a-a763-46de-a53c-634d0d7a46be">

**Comment by DevBobcorn** [comment]
My bad, i removed them from the project files but haven't yet added code to generate them in the right place. As a temporary fix, you can get the __Extra Data__ folder from a previous release and put it to the right path manually.

**Comment by codingwatching** [comment]
Thank you so much!
